## Importing Libraries

In [22]:
import pandas as pd
import numpy as np

## Reading the dataset

In [23]:
df = pd.read_csv('BAM_memory_dataset.csv')
df

x1  x2  x3  x4  x5  x6  x7  t1  t2  t3
0   1   1   1  -1   1   1   1  -1  -1  -1
1  -1  -1   1  -1  -1   1  -1  -1  -1   1
2   1  -1   1   1   1  -1   1  -1   1  -1
3   1  -1   1   1  -1   1   1  -1   1   1
4  -1   1   1   1  -1   1  -1   1  -1  -1
5   1   1  -1   1  -1   1   1   1  -1   1
6   1   1  -1   1   1   1   1   1   1  -1

In [24]:
input_df = df.iloc[:,:7]

output_df = df.iloc[:,-3:]

input_np = input_df.to_numpy()

output_np = output_df.to_numpy()

weights = input_np.transpose().dot(output_np)

weights_1 = []

idx = 0
for record in input_np.tolist():
    record_np = np.array(record)
    record_np.transpose(output_np)

print(weights)

[[-1  3 -1]
 [ 5 -3 -3]
 [-5 -1 -1]
 [ 3  3 -1]
 [-1  3 -5]
 [ 1 -3  1]
 [-1  3 -1]]


In [25]:
test_np = input_np.dot(weights)

test_np_list = test_np.tolist()

print(test_np_list)

test_np_result = []







for record in test_np_list:
    test_row = []
    for i in record:
        if i >= 0:
            test_row.append(1)
        else:
            test_row.append(-1)
    test_np_result.append(test_row)
        

for i in range(len(test_np_result)):
    print(f'{test_np_result[i]}-->{output_np.tolist()[i]}-->{test_np_result[i]==output_np.tolist()[i]}')

[[-5, -1, -9], [-9, -13, 11], [-11, 17, -7], [-7, 5, 5], [7, -13, 3], [13, 1, 1], [11, 7, -9]]
[-1, -1, -1]-->[-1, -1, -1]-->True
[-1, -1, 1]-->[-1, -1, 1]-->True
[-1, 1, -1]-->[-1, 1, -1]-->True
[-1, 1, 1]-->[-1, 1, 1]-->True
[1, -1, 1]-->[1, -1, -1]-->False
[1, 1, 1]-->[1, -1, 1]-->False
[1, 1, -1]-->[1, 1, -1]-->True


In [26]:
test_reverse = output_np.dot(weights.transpose()).tolist()

test_np_result = []

for record in test_reverse:
    test_row = []
    for i in record:
        if i >= 0:
            test_row.append(1)
        else:
            test_row.append(-1)
    test_np_result.append(test_row)

for i in range(len(test_np_result)):
    print(f'{test_np_result[i]}-->{input_np.tolist()[i]}-->{test_np_result[i]==input_np.tolist()[i]}')

[-1, 1, 1, -1, 1, 1, -1]-->[1, 1, 1, -1, 1, 1, 1]-->False
[-1, -1, 1, -1, -1, 1, -1]-->[-1, -1, 1, -1, -1, 1, -1]-->True
[1, -1, 1, 1, 1, -1, 1]-->[1, -1, 1, 1, 1, -1, 1]-->True
[1, -1, 1, -1, -1, -1, 1]-->[1, -1, 1, 1, -1, 1, 1]-->False
[-1, 1, -1, 1, 1, 1, -1]-->[-1, 1, 1, 1, -1, 1, -1]-->False
[-1, 1, -1, -1, -1, 1, -1]-->[1, 1, -1, 1, -1, 1, 1]-->False
[1, 1, -1, 1, 1, -1, 1]-->[1, 1, -1, 1, 1, 1, 1]-->False
